const keywords = [
    ['midi elbise',
    'saten midi elbise',
    'midi gömlek elbise',
    'çiçek desenli midi elbise',
    'midi mezuniyet elbisesi',
    'kolsuz midi elbise',
    'kabarık midi abiye',
    'midi parti elbisesi',
    'düz midi elbise',
    'v yaka midi elbise',
    'prenses model elbise midi',
    'midi elbise günlük',
    'kemerli midi elbise',
    'zarif midi elbise',
    'desenli midi elbise'],

    ['mini elbise',
    'siyah mini elbise',
    'kırmızı mini elbise',
    'beyaz mini elbise',
    'mini abiye elbise',
    'gece elbisesi mini',
    'askılı mini elbise',
    'çiçekli mini elbise',
    'ultra mini elbise',
    'uzun kollu mini elbise',
    'abiye mini elbise',
    'dar mini elbise',
    'dekolteli mini elbise',
    'mini saten elbise',
    'yazlık mini elbise',
    'mini mezuniyet elbise',
    'transparan mini elbise'
],
['uzun elbise',
'önü kısa arkası uzun elbise',
'siyah uzun elbise',
'beyaz uzun elbise',
'uzun yazlık elbise',
'uzun şifon elbise',
'günlük uzun elbise',
'uzun yırtmaçlı elbise',
'uzun hamile elbise',
'uzun triko elbise',
'uzun gömlek elbise',
'saten uzun elbise',
'kırmızı uzun elbise',
'askılı uzun elbise',
'uzun plaj elbisesi',
'dantelli nikah elbisesi uzun',
'uzun gece elbiseleri'
],
['hamile elbise',
'uzun hamile elbiseleri',
'hamile abiye elbise',
'beyaz hamile elbisesi',
'hamile salopet elbise',
'patırtı hamilelik abiye',
'yazlık hamile elbisesi',
'kışlık hamile elbisesi',
'hamile gece elbisesi',
'hamile çekimi için elbise',
'hamile jile elbise',
'hamile triko elbise',
'hamile düğün elbisesi',
'hamile şifon elbise',
'hamile günlük elbise',
'siyah hamile elbisesi',
'kırmızı hamile elbisesi'


]
]

module.exports = keywords

